apiVersion: v1
kind: Service
metadata:
  name: pact-postgres
  labels:
    app: pact-broker
spec:
  ports:
    - port: 5432
  selector:
    app: pact-broker
    tier: postgres-db
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pact-postgres
  labels:
    app: pact-broker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pact-broker
        tier: postgres-db
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: mypostgrespwd
        - name: POSTGRES_DB
          value: postgres
        name: postgres-db
        image: postgres
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always


