apiVersion: v1
kind: Service
metadata:
  name: pact-broker
  labels:
    app: pact-broker
spec:
  ports:
    - port: 80
  selector:
    app: pact-broker
    tier: frontend
  type: LoadBalancer
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pact-broker
  labels:
    app: pact-broker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pact-broker
        tier: frontend
    spec:
      containers:
      - env:
        - name: PACT_BROKER_DATABASE_ADAPTER
          value: postgres
        - name: PACT_BROKER_DATABASE_USERNAME
          value: postgres
        - name: PACT_BROKER_DATABASE_PASSWORD
          value: mypostgrespwd
        - name: PACT_BROKER_DATABASE_HOST
          value: pact-postgres
        - name: PACT_BROKER_DATABASE_NAME
          value: postgres
        - name: PACT_BROKER_BASIC_AUTH_USERNAME
          value: admin
        - name: PACT_BROKER_BASIC_AUTH_PASSWORD
          value: example
        image: dius/pact-broker:latest
        name: pact-broker
        ports:
        - containerPort: 80
      restartPolicy: Always

